apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: ticketing-microservices
build:
  googleCloudBuild:
    projectId: microservices-ticketing-417105
  artifacts:
    - image: us.gcr.io/microservices-ticketing-417105/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
