apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: ticketing-microservices
build:
  artifacts:
    - image: ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile

    - image: ticketing/client
      context: client
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - infra/k8s/*
