apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
spec:
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: ticketing/tickets
        env:
          - name: MONGO_URI
            value: mongodb://tickets-mongo-cluster-ip:27017/tickets_db
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
